# Generated by Django 4.1.3 on 2022-11-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postad',
            name='tag',
        ),
        migrations.AlterField(
            model_name='postad',
            name='ad_id',
            field=models.UUIDField(default='f76e4f0539d549aaba123629fe7e1e4d', editable=False),
        ),
    ]
