# Generated by Django 4.1.3 on 2022-11-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postad', '0002_alter_postad_ad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postad',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postad',
            name='ad_id',
            field=models.UUIDField(default='da10e0b5fbfb447fa03bae33ba4b0559', editable=False),
        ),
    ]
