# Generated by Django 4.1.3 on 2022-11-15 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postad', '0003_alter_postad_ad_id_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='ad_id',
            field=models.UUIDField(default='c2dc0777f47a47ee8d55b34a94277cd1', editable=False),
        ),
        migrations.CreateModel(
            name='ReportAdPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('subject', models.CharField(choices=[('Offensive content', 'Offensive content'), ('Fraud', 'Fraud'), ('Duplicate ad', 'Duplicate ad'), ('Product already sold', 'Product already sold'), ('Other', 'Other')], max_length=100)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postad.postad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
