# Generated by Django 4.1.3 on 2022-11-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postad', '0004_alter_postad_ad_id_reportadpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='ad_id',
            field=models.UUIDField(default='598211945d7340c993bae8a3ef2ed5f0', editable=False),
        ),
    ]
