# Generated by Django 4.1.3 on 2022-11-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postad', '0005_alter_postad_ad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='ad_id',
            field=models.UUIDField(default='e2d562e37bba48c9b5a2cecae65c2079', editable=False),
        ),
    ]
