# Generated by Django 4.1.3 on 2022-11-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postad', '0006_alter_postad_ad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='ad_id',
            field=models.UUIDField(default='71d4a37db4e8435da74abd231dd5a623', editable=False),
        ),
    ]
