# Generated by Django 4.1.3 on 2022-11-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postad', '0007_alter_postad_ad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='ad_id',
            field=models.UUIDField(default='2de8febeace242cfa08c1d37d36433c5', editable=False),
        ),
    ]
