# Generated by Django 4.1.3 on 2022-11-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postad', '0008_alter_postad_ad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='ad_id',
            field=models.UUIDField(default='cb562f6f9f964d79a1bbefc715871799', editable=False),
        ),
    ]
