# Generated by Django 4.1.3 on 2022-11-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postad', '0009_alter_postad_ad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='ad_id',
            field=models.UUIDField(default='25869ed719be475ca5434bcbda228f8e', editable=False),
        ),
    ]
