# Generated by Django 4.1.3 on 2022-11-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contactuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='users/default.png', null=True, upload_to='users/profile/'),
        ),
    ]
